name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  pages: write      # 给予 Pages 部署的写权限
  id-token: write   # 允许 ID Token 权限

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages  # 添加环境名称

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: _site/  # 这里假设构建的文件在 _site 文件夹中

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}